[colors.bright]
black = "#555753"
blue = "#729fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#ad7fa8"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[colors.normal]
black = "#2e3436"
blue = "#3465a4"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#75507b"
red = "#cc0000"
white = "#eaeaea"
yellow = "#c4a000"

[colors.primary]
background = "#000000"
foreground = "#eaeaea"

[cursor.style]
blinking = "On"

[font]
size = 12.0

[font.offset]
y = 4

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[window]
decorations = "none"
