# vim: set ft=yaml.ansible:
---
- name: get and deploy dotfiles
  hosts: localhost

  tasks:

  - name: ensure git, bash and vim are installed
    become: yes
    package:
      name: "{{ item }}"
      state: present
    loop:
    - git
    - bash
    - vim

  - name: stat .dotfiles
    stat:
      path: ~/.dotfiles
    register: dotfiles

  - name: clone .dotfiles repository
    git:
      repo: https://github.com/fionn/.dotfiles.git
      version: master
      recursive: yes
      dest: ~/.dotfiles
    when: not dotfiles.stat.exists

  - name: stat .bashrc
    stat:
      path: ~/.bashrc
    register: bashrc

  - name: backup .bashrc
    command: mv ~/.bashrc ~/.bashrc.backup.{{ ansible_date_time.epoch }}
    when: bashrc.stat.exists

  - name: make symbolic links
    file:
      src: ~/.dotfiles/{{ item }}
      dest: ~/{{ item }}
      state: link
    loop:
    - .vimrc
    - .vim
    - .bashrc
    - .bash_aliases
    - .gitconfig
    - .mypy.ini
