[lint]

select = ["ALL"]
ignore = [
    "S", "I", "T",
    "FA", "EM", "PT",
    "ANN", "PTH",
    "ERA001",
    "COM812",
    "TRY003",
    "PERF203",
    "ISC002",
    "E741",
    "Q003",
    "D105", "D107", "D202", "D203", "D205", "D212", "D400", "D401", "D403", "D415",
    "UP013", "UP014",
    "RUF001", "RUF002", "RUF003",
    "PLW2901",
    "PLR2004"
]

[lint.per-file-ignores]
"__init__.py" = ["F403"]
