set secure
set modelines=5
set encoding=utf-8
scriptencoding utf-8

noremap <leader>s :source ~/.vim/vimrc<CR>
nnoremap Q <Nop>
nnoremap <silent><CR> :nohlsearch<CR><CR>
nnoremap <leader>u :UndotreeToggle<CR>
inoremap <C-v> <Nop>
onoremap j gj
onoremap k gk
command W w
command Q q
command Wq wq

set clipboard=unnamedplus

set number
set tabstop=4
set shiftwidth=4
set softtabstop=-1
set expandtab
set shiftround
set autoindent
set breakindent
set nojoinspaces
set backspace=indent,eol,start
set ruler
set smoothscroll

set ignorecase
set smartcase
set incsearch
set hlsearch

set spelllang=en_gb
set showcmd
set wrap
set linebreak
set lazyredraw
set redrawtime=4000
set updatetime=100

set splitbelow
set splitright

set wildmode=longest,list,full
set wildmenu
set wildignore+=*.swp,*.o,*.aux,*.toc,*.pdf,*.so,*.pyc,*/__pycache__,*/venv
set tags+=tags;

set undofile
if !has("nvim") && &undodir == "."
    let $XDG_CACHE_HOME = $XDG_CACHE_HOME ?? $HOME . "/.cache"
    set undodir=$XDG_CACHE_HOME/vim/undo/
    if !isdirectory(&undodir)
        call mkdir(&undodir, "p", 0700)
    endif
    set directory=$XDG_CACHE_HOME/vim/swap//
    if !isdirectory(&directory)
        call mkdir(&directory, "p", 0700)
    endif
endif

if !has("nvim")
    let $XDG_DATA_HOME = $XDG_DATA_HOME ?? $HOME . "/.local/share"
    set packpath^=$XDG_DATA_HOME/vim/site

    " To install minpack for the first time:
    " mkdir -p ~/.local/share/vim/site/pack/minpac/opt
    " git clone https://github.com/k-takata/minpac.git ~/.local/share/vim/site/pack/minpac/opt/minpac

    function! PackInit() abort
        packadd minpac
        call minpac#init()
        call minpac#add("k-takata/minpac", {"type": "opt"})
    endfunction

    command! PackUpdate call PackInit() | call minpac#update()
    command! PackClean  call PackInit() | call minpac#clean()
    command! PackStatus packadd minpac  | call minpac#status()
endif

set hidden
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_winsize = 25
let g:netrw_altv = 1
let g:netrw_special_syntax = 1
let g:netrw_list_hide = '.*\.swp$,.*\.aux$,.*\.toc$,.*\.pdf$,.\*.sig$,.*\.so$,.*\.o$,__pycache__/$,.mypy_cache/$,venv/$,.git/$'

set completeopt=longest,menu,noinsert

syntax on
set list listchars=tab:\ \ ,trail:·
filetype plugin indent on
augroup vimrc | autocmd!
    autocmd InsertLeave * redraw!
    autocmd FileType csv setlocal noexpandtab softtabstop=0
    autocmd FileType tags setlocal tabstop=16 shiftwidth=16 softtabstop=16
    autocmd FileType python setlocal completeopt-=preview
    autocmd FileType gitcommit setlocal spell textwidth=72 formatoptions=tnwa
    autocmd FileType gitcommit highlight SpellCap ctermbg=none
    autocmd FileType markdown setlocal spell
    autocmd FileType markdown highlight Title cterm=bold
    autocmd FileType mail setlocal spell textwidth=72 formatoptions+=watqc
    autocmd FileType mail match ErrorMsg '\s\+$'
augroup END

let g:tex_flavor = "latex"

set omnifunc=ale#completion#OmniFunc

nnoremap <leader>] :ALEGoToDefinition<CR>

nmap <F8> <Plug>(ale_fix)

let g:ale_completion_enabled = 1
let g:ale_fixers = {"*": ["remove_trailing_lines", "trim_whitespace"],
                    \ "terraform": ["terraform", "remove_trailing_lines", "trim_whitespace"],
                    \ "rust": ["rustfmt", "trim_whitespace", "remove_trailing_lines"]}
let g:ale_linters_ignore = {"tex": ["lacheck"]}
let g:ale_fix_on_save = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_enabled = 1
let g:ale_virtualenv_dir_names = ["venv"]
let g:ale_echo_msg_format = "[%linter%] %code: %%s "
let g:ale_sign_error = "🞩"
let g:ale_sign_warning = "⚠"
let g:ale_sign_info = "ⓘ"
let g:ale_virtualtext_cursor = "disabled"
let g:ale_use_neovim_diagnostics_api = 0

let g:terraform_align = 1

let g:markdown_fenced_languages = ["python", "bash"]

let &t_SI = "\e[5 q"
let &t_EI = "\e[1 q"
let &t_SR = "\e[3 q"
set ttimeoutlen=1

packadd grb256
set notermguicolors
colorscheme ff256
set signcolumn=yes
set colorcolumn=81
set cursorline

nnoremap <F2>:set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

if has("mouse")
    set mouse=a
    if !has("nvim")
        set ttymouse=sgr
    endif
endif

if has("macunix")
    set clipboard=unnamed
endif

if empty($WAYLAND_DISPLAY) && has("X11")
    augroup x11 | autocmd!
        autocmd VimLeave * call system("xclip -selection clipboard -r", getreg("+"))
    augroup END
endif

if exists(":cryptmethod")
    set cryptmethod=blowfish2
    augroup encrypted | autocmd!
        autocmd BufReadPost * if &key != "" | set noswapfile nowritebackup viminfo= nobackup noshelltemp history=0 | endif
    augroup END
endif

nmap <C-L> :call <SID>SynStack()<CR>
function! <SID>SynStack()
    if !exists("*synstack")
        return
    endif
    echo map(synstack(line("."), col(".")), "synIDattr(v:val, \"name\")")
endfunc

cabbrev w!! w !sudo tee > /dev/null %
